# JSON request validation for PROD ACL inputs.
VALID_PLATFORM_ENVIRONMENT=prod
VALID_MODES=UPSERT,DELETE
CATALOG_ROOT=main/topics
GENERATED_ACL_FILE=files/elc-acl.json
VALID_RESOURCE_TYPES=TOPIC,GROUP,CLUSTER,TRANSACTIONAL_ID,DELEGATION_TOKEN
VALID_PATTERN_TYPES=LITERAL,PREFIXED
VALID_OPERATIONS=ALL,READ,WRITE,CREATE,DELETE,ALTER,DESCRIBE,CLUSTER_ACTION,DESCRIBE_CONFIGS,ALTER_CONFIGS,IDEMPOTENT_WRITE
VALID_PERMISSIONS=ALLOW,DENY